@intern challenges/three
yashthipsay/Forta_Bots_Challenges pull request #6
Opened 2024-07-10 08:48 UTC by yashthipsay

2024-07-13 11:07 UTC, RCantu92 requested changes
Hey Yash, I understand what you're attempting to do with this implementation of the bot. However, this won't work in production how you expect. That is because it won't be the same bot instance that is monitoring Ethereum as would be monitoring Optimism and Arbitrum. They would be three separate instances, and as such, wouldn't save state across one another. I.e. the array of alerts that you're updating and then fetching from would be isolated to each instance and not accessible by the other two instances.

So the approach is on the right path, but it does need further work. I would suggest you look more into the `getAlerts` method from the Forta SDK that you are attempting to implement your own version of. Remember, you would be able to use this in production. 😉

2024-07-18 08:39 UTC, Vxatz requested changes

2024-07-19 10:12 UTC, Vxatz requested changes

2024-07-19 10:12 UTC, Vxatz commented on Challenge-3/src/helper.ts
> +      alertId: "L2-SUPPLY",
The alert ID is incorrect, as this is trying to fetch the L2 alerts while being on L2.

2024-07-19 10:12 UTC, Vxatz commented on Challenge-3/src/findings.ts
> +export const createL2Finding = (
```suggestion
export const createL1Finding = (
```

Should be "L1"

2024-07-19 10:12 UTC, Vxatz commented on Challenge-3/src/agent.ts
> +      findings.push(createL2Finding(optBalance, abtBalance));
There's one thing that I've missed yesterday, and we probably have discussed it, I think.

We shouldn't be emitting an Info alert on every single block, as in most blocks the balances aren't expected to change. We should only be firing one when there's a balance change.

2024-07-19 10:12 UTC, Vxatz commented on Challenge-3/src/helper.ts
> +    return totalSupply.toString();
This returned string is not really used anywhere

2024-07-19 10:12 UTC, Vxatz commented on Challenge-3/src/agent.ts
> +      await helperInstance.getL2Supply(
The function doesn't only fetch the L2 supply, but also potentially creates a high severity finding. You could update both the comment and the method name to indicate this.

2024-07-19 10:12 UTC, Vxatz commented on Challenge-3/src/findings.ts
> +    protocol: `${network}`,
No need to use backticks on this

2024-07-22 21:26 UTC, Vxatz requested changes

2024-07-22 21:26 UTC, Vxatz commented on Challenge-3/src/agent.ts
> +      if (prevOptBalance !== optBalance || prevAbtBalance !== abtBalance || !prevOptBalance || !prevAbtBalance) {
```suggestion
      if (prevOptBalance !== optBalance || prevAbtBalance !== abtBalance) {
```

The "undefined" checks are redundant, as they would still be "not equal" to the last fetched balance.

2024-07-22 21:26 UTC, Vxatz commented on Challenge-3/src/helper.ts
> +      alertId: "L2-SUPPLY",
Unresolved the comment above, as the `alertId` is still incorrect.

2024-07-29 21:07 UTC, Vxatz approved these changes
LGTM 🎉

2024-07-30 03:07 UTC, merged